gcp_credentials: ENCRYPTED[5ee9e22237c8368fdae53b368a38509d62a168e1b5a8162a9bd8dfef5e874a4f41cd8235d498b99d2c2860c77e06ecd1]

gce_instance:
  image_project: ubuntu-os-cloud
  image_family: ubuntu-2404-lts-arm64
  architecture: arm64
  zone: us-east1-b
  type: c4a-standard-16
  disk: 60
  spot: true

# -- PR tasks

pr_check_commits_task:
  skip: $CIRRUS_PR == ""
  name: (PR) Check commits structure
  alias: pr_check_commits
  timeout_in: 240m
  env:
    GH_TOKEN: ""
  dependencies_script:
    - set -eo pipefail
  # No need to clone.
  clone_script: []
  test_script: |
    url=https://api.github.com/repos/CHERIoT-Platform/cheri-rust/pulls/$CIRRUS_PR
    commits=$(curl -s -H "Accept: application/vnd.github+json" $url | jq '.commits')
    if [[ $commits -ne 1 ]]; then
      echo "Expected a single commit, found $commits"
      echo "In order to facilitate cherry-picking commits into other branches,"
      echo "please squash your commits into a single one."
      exit 1;
    fi

# -- End PR tasks

x_test_task:
  name: Run ./x test
  alias: x_test
  # TODO(xdoardo): Figure out when it makes sense to have this dependency, or
  #   how that dependency should actually work. Having this dependency would
  #   pretty much mean making every PR that merges changes on `beta` to `main`
  #   to have failing CI, which would be the reason why we want to make PRs and
  #   not direct pushes in the first place.
  # depends_on: (PR) Check commits structure
  timeout_in: 240m
  dependencies_script:
    - set -eo pipefail
    - apt-get update
    - apt-get install -y pkg-config clang ninja-build lld cmake ccache perl libssl-dev
  gen_bootstrap_script: ./cheri/gen_bootstrap.py -v
  setup_env_script:
    - echo "CCACHE_REMOTE_STORAGE=http://${CIRRUS_HTTP_CACHE_HOST}/${CIRRUS_OS}/" >> $CIRRUS_ENV
    - echo "CCACHE_REMOTE_ONLY=1" >> $CIRRUS_ENV
  check_env_script: env
  pull_main_script: git fetch origin main:refs/remotes/origin/main
  rust_check_script: CC="clang" CXX="clang++" ./x check
  build_fmt_script: CC="clang" CXX="clang++" ./x build rustfmt
  rust_test_tidy_script: CC="clang" CXX="clang++" ./x test tidy
  rust_test_script: CC="clang" CXX="clang++" ./x test --skip src/tools/linkchecker --skip tests/rustdoc-ui --skip tests/run-make --skip tidy

build_core_task:
  name: Build `core` library  for `riscv32cheriot-unknown-cheriotrtos`
  alias: build_core
  depends_on:
    - x_test
  timeout_in: 240m
  env:
    CIRRUS_CLONE_DEPTH: "1"
  dependencies_script:
    - set -eo pipefail
    - apt-get update
    - apt-get install -y clang ninja-build lld cmake ccache perl
  gen_bootstrap_script: ./cheri/gen_bootstrap.py -v
  setup_env_script:
    - echo "CCACHE_REMOTE_STORAGE=http://${CIRRUS_HTTP_CACHE_HOST}/${CIRRUS_OS}/" >> $CIRRUS_ENV
    - echo "CCACHE_REMOTE_ONLY=1" >> $CIRRUS_ENV
  check_env_script: env
  pull_main_script: git fetch origin main:refs/remotes/origin/main --depth 1
  build_script: CC="clang" CXX="clang++" ./x build compiler std --target=riscv32cheriot-unknown-cheriotrtos

run_cheri_tests_task:
  name: Run CHERIoT-specific tests
  alias: run_cheri_tests
  depends_on:
    - build_core
  timeout_in: 240m
  env:
    CIRRUS_CLONE_DEPTH: "1"
    CARGO_HOME: /tmp/cargo
    RUSTUP_HOME: /tmp/cargo
    XMAKE_ROOT: "y"
  dependencies_script:
    - set -eo pipefail
    - apt-get update
    - apt-get install -y clang ninja-build lld cmake ccache perl opam z3 libgmp-dev
  install_xmake_script: curl -fsSL https://xmake.io/shget.text | bash || true # The installer will fail without any informations.
  verify_xmake_script: /root/.local/bin/xmake --version
  install_rust_script: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | bash -s -- -y
  verify_rust_script: . "$CARGO_HOME/env" && cargo --version
  build_sail_sim_script:
    - git clone --recurse-submodules --depth=1 https://github.com/CHERIoT-Platform/cheriot-sail
    - opam init --reinit --bypass-check --disable-sandboxing --disable-shell-hook
    - eval $(opam env)
    - opam install sail --confirm-level=unsafe-yes
    - cd cheriot-sail && make csim && cp c_emulator/cheriot_sim /usr/local/bin
  gen_bootstrap_script: ./cheri/gen_bootstrap.py --build-clang -v
  setup_env_script:
    - echo "CCACHE_REMOTE_STORAGE=http://${CIRRUS_HTTP_CACHE_HOST}/${CIRRUS_OS}/" >> $CIRRUS_ENV
    - echo "CCACHE_REMOTE_ONLY=1" >> $CIRRUS_ENV
  check_env_script: env
  pull_main_script: git fetch origin main:refs/remotes/origin/main --depth 1
  build_rustc_script: CC="clang" CXX="clang++" ./x build compiler std --target=riscv32cheriot-unknown-cheriotrtos
  run_x_cheriot_tests_script: CC="clang" CXX="clang++" ./x test tests/codegen-llvm --target=riscv32cheriot-unknown-cheriotrtos --skip src/tools/linkchecker
  build_test_runner_script: cd ./cheri/tests/runner && . "$CARGO_HOME/env" && cargo build --release
  run_tests_script: cd ./cheri/tests && ./runner/target/release/cheriot-runner -vvvvv .
    --sysroot=../../build/host/llvm
    --rustc=../../build/host/stage1/bin/rustc
    --xmake=/root/.local/bin/xmake

release_task:
  timeout_in: 120m
  depends_on: run_cheri_tests
  only_if: ($CIRRUS_PR == "") && ($CIRRUS_BRANCH == "beta")
  matrix:
    # Warning: the name of the tasks must mach the output of $(uname -p) in the runners.
    - name: Build and upload artefact x86_64
      gce_instance:
        image_project: ubuntu-os-cloud
        image_family: ubuntu-2404-lts-amd64
        architecture: amd64
        zone: us-east1-b
        type: t2d-standard-16
        disk: 60
        spot: true
    - name: Build and upload artefact aarch64
      gce_instance:
        image_project: ubuntu-os-cloud
        image_family: ubuntu-2404-lts-arm64
        architecture: arm64
        zone: us-east1-b
        type: c4a-standard-16
        disk: 60
        spot: true
  env:
    NINJA_STATUS: "%p [%f:%s/%t] %o/s, %es: "
    CIRRUS_CLONE_DEPTH: 1
  dependencies_script:
    - set -eo pipefail
    - apt-get update
    - apt-get install -y pkg-config clang ninja-build lld cmake ccache perl libssl-dev
  build_rustc_script:
    - |
      cat <<EOF > bootstrap.toml
      profile = "compiler"
      change-id = "ignore"

      [llvm]
      targets = "all"
      experimental-targets = ""
      download-ci-llvm = false
      build-config = {CMAKE_C_COMPILER="clang", CMAKE_CXX_COMPILER="clang++"}

      [build]
      ccache = true
      docs = false
      target = ["riscv32cheriot-unknown-cheriotrtos"]
      tools = ["cargo", "rustfmt"]

      [dist]
      compression-formats = ["gz"]

      [rust]
      channel = "dev"
      std-features = ["compiler-builtins-mem"]
      strip = true
      dist-src = false
      optimize = "z"
      EOF
    - ./x dist --target=riscv32cheriot-unknown-cheriotrtos
    - ./x dist cargo --target=riscv32cheriot-unknown-cheriotrtos
    - rm -r build/dist/rust-src* build/dist/rust-dev* build/dist/rustc-dev* build/dist/rustc-docs*
  binaries_artifacts:
    path: "build/dist/**"
